service: bytabit-serverless

provider:
  name: aws
  runtime: nodejs6.10

  environment:
      OFFER_TABLE: ${self:service}-${opt:stage, self:provider.stage}-offer
      PROFILE_TABLE: ${self:service}-${opt:stage, self:provider.stage}-profile
      TRADE_TABLE: ${self:service}-${opt:stage, self:provider.stage}-trade

  iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource:
          - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.OFFER_TABLE}"
          - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.PROFILE_TABLE}"
          - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TRADE_TABLE}"
          - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TRADE_TABLE}/index/sellerIndex"
          - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TRADE_TABLE}/index/buyerIndex"
          - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TRADE_TABLE}/index/arbitratorIndex"

functions:
  profiles-create:
      handler: src/main/js/profile/create.create
      events:
        - http:
            path: profiles/{pubKey}
            method: put
            cors: true
  profiles-list:
      handler: src/main/js/profile/list.list
      events:
        - http:
            path: profiles
            method: get
            cors: true
  profiles-delete:
      handler: src/main/js/profile/delete.delete
      events:
        - http:
            path: profiles/{pubKey}
            method: delete
            cors: true

  offers-create:
      handler: src/main/js/offer/create.create
      events:
        - http:
            path: offers/{sellerEscrowPubKey}
            method: put
            cors: true
  offers-list:
      handler: src/main/js/offer/list.list
      events:
        - http:
            path: offers
            method: get
            cors: true
  offers-delete:
      handler: src/main/js/offer/delete.delete
      events:
        - http:
            path: offers/{sellerEscrowPubKey}
            method: delete
            cors: true
  trades-create:
      handler: src/main/js/trade/create.create
      events:
        - http:
            path: trades/{sellerEscrowPubKey}
            method: put
            cors: true
  trades-list:
      handler: src/main/js/trade/list.list
      events:
        - http:
            path: trades
            method: get
            cors: true

resources:
  Resources:

    BytabitProfileTable:
          Type: 'AWS::DynamoDB::Table'
          DeletionPolicy: Delete
          Properties:
            TableName: ${self:provider.environment.PROFILE_TABLE}
            AttributeDefinitions:
              -
                AttributeName: pubKey
                AttributeType: S
              -
                AttributeName: updated
                AttributeType: N
            KeySchema:
              -
                AttributeName: pubKey
                KeyType: HASH
              -
                AttributeName: updated
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

    BytabitOfferTable:
          Type: 'AWS::DynamoDB::Table'
          DeletionPolicy: Delete
          Properties:
            TableName: ${self:provider.environment.OFFER_TABLE}
            AttributeDefinitions:
              -
                AttributeName: sellerEscrowPubKey
                AttributeType: S
              -
                AttributeName: updated
                AttributeType: N
            KeySchema:
              -
                AttributeName: sellerEscrowPubKey
                KeyType: HASH
              -
                AttributeName: updated
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

    BytabitTradeTable:
          Type: 'AWS::DynamoDB::Table'
          DeletionPolicy: Delete
          Properties:
            TableName: ${self:provider.environment.TRADE_TABLE}
            AttributeDefinitions:
              -
                AttributeName: escrowAddress
                AttributeType: S
              -
                AttributeName: sellerProfilePubKey
                AttributeType: S
              -
                AttributeName: buyerProfilePubKey
                AttributeType: S
              -
                AttributeName: arbitratorProfilePubKey
                AttributeType: S
              -
                AttributeName: updated
                AttributeType: N
            KeySchema:
              -
                AttributeName: escrowAddress
                KeyType: HASH
              -
                AttributeName: updated
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
            GlobalSecondaryIndexes:
              -
                IndexName: sellerIndex
                KeySchema:
                  -
                    AttributeName: sellerProfilePubKey
                    KeyType: HASH
                  -
                    AttributeName: updated
                    KeyType: RANGE
                Projection:
                  ProjectionType: ALL
                ProvisionedThroughput:
                  ReadCapacityUnits: "1"
                  WriteCapacityUnits: "1"
              -
                IndexName: buyerIndex
                KeySchema:
                  -
                    AttributeName: buyerProfilePubKey
                    KeyType: HASH
                  -
                    AttributeName: updated
                    KeyType: RANGE
                Projection:
                  ProjectionType: ALL
                ProvisionedThroughput:
                  ReadCapacityUnits: "1"
                  WriteCapacityUnits: "1"
              -
                IndexName: arbitratorIndex
                KeySchema:
                  -
                    AttributeName: arbitratorProfilePubKey
                    KeyType: HASH
                  -
                    AttributeName: updated
                    KeyType: RANGE
                Projection:
                  ProjectionType: ALL
                ProvisionedThroughput:
                  ReadCapacityUnits: "1"
                  WriteCapacityUnits: "1"

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: test.bytabit.net
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true