service: bytabit-serverless

provider:
  name: aws
  runtime: nodejs6.10

  environment:
      DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

  iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
      handler: src/main/js/offers/create.create
      events:
        - http:
            path: offers
            method: post
            cors: true
  list:
        handler: src/main/js/offers/list.list
        events:
          - http:
              path: offers
              method: get
              cors: true
  delete:
      handler: src/main/js/offers/delete.delete
      events:
        - http:
            path: offers/{sellerEscrowPubKey}
            method: delete
            cors: true

resources:
  Resources:
    BytabitDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          -
            AttributeName: sellerEscrowPubKey
            AttributeType: S
        KeySchema:
          -
            AttributeName: sellerEscrowPubKey
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

